### ISSUE TITLE
Neko room doesn't connect

### ISSUE THREAD

**Issue by joaofrenor** [m1k1o/neko-rooms#10]
I create a room and when I try to log in it fails and I got timed out
Tried using docker and install bash

Is there a way to enable debug to see what is not working?
Tried Digital Ocean and AWS

Neko alone works just fine but with rooms doesn't

**Comment by m1k1o** [comment]
Cleint and server logs (for each room) are verbose enough to catch error connection errors. You could spawn new room with environmentvariable `NEKO_DEBUG=true` using neko rooms, to enable debug mode.

**Comment by m1k1o** [comment]
Mobile browser has to support WebRTC and VP8. Tried with Safari on iPhone 11, it works. But the UX for mobile is not great. Controlling is not possible with iPhones. Desktop usage is preferred.

**Comment by joaofrenor** [comment]
Tried using Chrome iPhone XS, I had to open pip to enable enable it but I cannot find audio button

**Comment by m1k1o** [comment]
Some controls are not available on the phone, because the screen is so small. It was never designed on small screens, so a rewrite for mobile design would be needed.

**Comment by joaofrenor** [comment]
So, Is there a way to enable audio on iPhone? When I join its not autoplaying either with sound?

**Comment by m1k1o** [comment]
Looks like that feature is not availabe. You should be able to fullscreen it and unmute there, but it does not work. Anyway, this is not issue of neko-rooms but the neko itself. So you can open new issue there and we'll take a look.

Back to original issue, so connecting works?

**Comment by joaofrenor** [comment]
Yes
