### ISSUE TITLE
IP ban working in Neko standalone but not with Neko-Rooms

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko-rooms#107]
Hi. the IP ban function works fine when running Neko standalone installed without Neko-Rooms, but in a room launched by Neko-Rooms, an IP ban on one user bans everyone and then no one can enter the room. It's as if it's not detecting individual IP addresses and the ban happens on an address that everyone uses.

It's not a server issue because I've tried it on both Linode VPS and Vultr making sure I'm not behind any NodeBalance or reverse proxy and I checked with Linode techs and they figure it should be a config issue with Neko, and as stated it works fine with Neko standalone so it should be something in the Neko-Rooms installation script or some other Neko-Rooms config setting that I need to check to get it to work with Neko-Rooms.

Any help is much appreciated. Thanks in advance.

**Comment by m1k1o** [comment]
Hi, are you using neko-rooms with or without traefik? When you mention `Neko-Rooms installation script` then i assume you are using it with traefik.

**Comment by m1k1o** [comment]
I added `NEKO_PROXY` to neko rooms. Please pull latest code, latest images and restart traefik with new config, then recreate rooms. It should now see the real IP.

**Comment by SpiderSuave** [comment]
> I added `NEKO_PROXY` to neko rooms. Please pull latest code, latest images and restart traefik with new config, then recreate rooms. It should now see the real IP.

Thank you! That fixed it and it works perfectly well. Much appreciated.
