### ISSUE TITLE
neko-rooms as a standalone Rest API 

### ISSUE THREAD

**Issue by mtami-zoor** [m1k1o/neko-rooms#109]
Hello Everyone,

I'm aware that neko-rooms is designed for users who prefer no-code solutions. However, I'm interested in utilizing its backend Go application as a Rest API, independent of the Frontend Vue component. Could anyone direct me to any tutorials or online resources that can assist me in this? My challenge is that I have no prior experience with Go.

Also, is there any documentation for the full configuration that can be set on the backend side?

**Comment by m1k1o** [comment]
Hello,

neko rooms is equally designed for people that prefer no-code solutions as well as for powerful API users.

Here is our [OpenAPI](https://openapi.tools/) specification https://github.com/m1k1o/neko-rooms/blob/master/OpenApi.yml.

This specification can be exported to a nice docs page that you can browse or directly to client in the programming language of your choice. See https://github.com/OpenAPITools/openapi-generator. For example, I generate API client for javascript [here](https://github.com/m1k1o/neko-rooms/blob/74fe2d7eab00622ec48a05c3f12fbdda5343f490/dev/api-gen).

**Comment by mtami-zoor** [comment]
Thank you very much!!
Appreciate your helpful guidance.
