### ISSUE TITLE
What is the effect of memory, CPUs and shared memory settings in Neko-Rooms?

### ISSUE THREAD

**Issue by SpiderSuave** [m1k1o/neko-rooms#112]
Thank you for the info and sorry in advance if this was already documented somewhere.

**Comment by SpiderSuave** [comment]
Thank you. If running Neko with KDE image on Linode VPS with dedicated 8 CPU + 16 GB RAM, for best performance should I just leave the default settings of N/A for memory and CPUs and 2 GB for shared memory or do you recommend something else? Thanks again.

**Comment by m1k1o** [comment]
The default settings of N/A means, there is no limit. You can always increate shared memory if you see that it does not keep up, but I havent seen that it would have performance issues.
