### ISSUE TITLE
Server error Error response from daemon: network traefik not found 

### ISSUE THREAD

**Issue by iamliterallyacat** [m1k1o/neko-rooms#114]
I wanted to set it up on my homelab under arch so I simply assumed it was possible to remove the traefik part and just use Nginxproxymanager; it worked until I wanted to create a room.
Is there any workaround?
I think it might be helpful to add that I went through the install script you provided to find the docker-compose.yml

**Comment by m1k1o** [comment]
Please refer to this comment: https://github.com/m1k1o/neko-rooms/issues/71#issuecomment-1225495759 It's just a default name of the network that is called `traefik` for backward compatibility. 

The install script is currently only for traefik deployment, `docker-compose.yml` uses a [different name](https://github.com/m1k1o/neko-rooms/blob/74fe2d7eab00622ec48a05c3f12fbdda5343f490/docker-compose.yml#L18C1-L18C53) of the network.
