### ISSUE TITLE
How to add tor/xfsc to neko rooms

### ISSUE THREAD

**Issue by faikmalik** [m1k1o/neko-rooms#117]
Trying to add other images to rooms. iv tried 

docker pull m1k1o/neko:xfce
docker-compose pull
docker-compose up -d

but the list doesnt seem to add xfce to my options

**Comment by m1k1o** [comment]
You need to specify it in `NEKO_ROOMS_NEKO_IMAGES`. See https://github.com/m1k1o/neko-rooms/issues/41.
