### ISSUE TITLE
chrome policy update

### ISSUE THREAD

**Issue by faikmalik** [m1k1o/neko-rooms#119]
Hi im following [this tutorial](https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md#how-can-it-be-used)

 according to tutorial here is my config
![image](https://github.com/m1k1o/neko-rooms/assets/5184656/0b6dc9fd-c166-4495-8fc2-424c99d72a8b)

**here is my policies.json @ /opt/neko-rooms/data/templates/policies.json**
`
  "HomepageLocation": "my def domain",
  "AutoFillEnabled": false,
  "AutofillAddressEnabled": false,
  "AutofillCreditCardEnabled": false,
  "BrowserSignin": 0,
  "DefaultNotificationsSetting": 2,
  "DeveloperToolsAvailability": 2,
  "EditBookmarksEnabled": false,
  "FullscreenAllowed": true,
  "IncognitoModeAvailability": 1,
  "SyncDisabled": true,
  "AutoplayAllowed": true,
  "BrowserAddPersonEnabled": false,
  "BrowserGuestModeEnabled": false,
  "DefaultPopupsSetting": 2,
  "DownloadRestrictions": 0,
  "VideoCaptureAllowed": false,
  "AllowFileSelectionDialogs": false,
  "PromptForDownloadLocation": true,
  "BookmarkBarEnabled": false,
  "PasswordManagerEnabled": false,
  "URLBlacklist": [
  ],
  "ExtensionInstallForcelist": [
      "lpcaedmchfhocbbapmcbpinfpgnhiddi;https://clients2.google.com/service/update2/crx",
      "cjpalhdlnbpafiamejdnhcphjbkeiagm;https://clients2.google.com/service/update2/crx",
      "fjoaledfpmneenckfbpdfhkmimnjocfa;https://clients2.google.com/service/update2/crx"
  ],
  "ExtensionInstallWhitelist": [
      "lpcaedmchfhocbbapmcbpinfpgnhiddi",
      "cjpalhdlnbpafiamejdnhcphjbkeiagm",
      "fjoaledfpmneenckfbpdfhkmimnjocfa"
  ],
  "ExtensionInstallBlacklist": [
      "*"
  ]
}
`

iv manually copied same file to /opt/neko-rooms/data/faik which is my room name. for some reason it wasnt auto created

**here is my .env**

NEKO_ROOMS_EPR=59000-59100
NEKO_ROOMS_TRAEFIK_DOMAIN=neko.oemnavigations.net
NEKO_ROOMS_TRAEFIK_ENTRYPOINT=websecure
NEKO_ROOMS_TRAEFIK_NETWORK=neko-rooms-traefik
NEKO_ROOMS_TRAEFIK_CERTRESOLVER=lets-encrypt
NEKO_ROOMS_NEKO_IMAGES=m1k1o/neko:firefox m1k1o/neko:chromium m1k1o/neko:google-chrome m1k1o/neko:vlc m1k1o/neko:xfce m1k1o/neko:tor-browser
NEKO_ROOMS_MOUNTS_WHITELIST="/home /media /opt/neko-rooms/data/templates/ /etc/opt/chrome/policies/managed/policies.json"

**here is my docker-compose.yml**

version: "3.5"

networks:
  default:
    attachable: true
    name: "${NEKO_ROOMS_TRAEFIK_NETWORK}"

services:
  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    environment:
      - "TZ"
    ports:
      - target: 80
        published: 80
        protocol: "tcp"
        mode: "host"
      - target: 443
        published: 443
        protocol: "tcp"
        mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./usersfile:/usersfile:ro"
      - "./acme.json:/acme.json"
      - "./config:/config"

  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "NEKO_ROOMS_STORAGE_ENABLED=true"
      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"
      - "NEKO_ROOMS_STORAGE_EXTERNAL=/opt/neko-rooms/data"
    env_file:
      - ".env"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/neko-rooms/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.neko-rooms.rule=Host(`${NEKO_ROOMS_TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.neko-rooms.tls=true"
      - "traefik.http.routers.neko-rooms.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.neko-rooms.middlewares=basicauth@file"

**PROBLEM**

if you see in config iv removed the default policy page and file path restriction from .docker folder. im trying to let users download a file to my file system. aditionally i want to add my own set of extensions in the force install extensions. but for some reason its still picking up default policies.

any help is appreciated

**Comment by faikmalik** [comment]
hi. thanks for reply. im aware of white list. did that for testing.

yeah it was a mistake here. verified the file and its ok. but i thought for a second and questioned my self.

as for the policy path. im not native to linux. i was fiddling with paths. actually the path you gave above gives me an error like this

![image](https://github.com/m1k1o/neko-rooms/assets/5184656/0b6c95c5-fdb9-417f-9d03-bb556cf15939)

thanks for the reply

**Comment by m1k1o** [comment]
Sounds like you are mounting directory to a file. And it does not seem to be valid path `/opt/neko-rooms/data/rooms/rrr1` seems like a `private` path not `template` you wanted to use. Can you check if thats correct?
