### ISSUE TITLE
Install failed: Connection timed out.

### ISSUE THREAD

**Issue by alfaputra27** [m1k1o/neko-rooms#120]
Help me sir, erorr after run script :

wget -O neko-rooms.sh https://raw.githubusercontent.com/m1k1o/neko-rooms/master/traefik/install
sudo bash neko-rooms.sh

Erorr :
--2024-03-12 10:44:10--  https://raw.githubusercontent.com/m1k1o/neko-rooms/master/traefik/install
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8002::154, 2606:50c0:8003::154, 2606:50c0:8001::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8002::154|:443...
failed: Connection timed out.

**Comment by m1k1o** [comment]
Looks like your server does not have internet connection.

**Comment by alfaputra27** [comment]
command appears "Enter your domain name: (e.g. example.com)" If I use IPv4, is it mandatory to fill it with water?

**Comment by m1k1o** [comment]
For https (lets encrypt) you need domain name. It does not work with only ips.

**Comment by alfaputra27** [comment]
![Screenshot 2024-03-12 190644](https://github.com/m1k1o/neko-rooms/assets/54224337/c258185f-b34d-4882-a170-a65e7d03a67c)

**Comment by m1k1o** [comment]
It looks like docker is not running.
