### ISSUE TITLE
[Question] any feature like 'open with neko' ?

### ISSUE THREAD

**Issue by narainaDewasi** [m1k1o/neko-rooms#122]
hey @m1k1o 
Just out of curiosity, I'm asking if there's any feature similar to 'Open with Neko', allowing users to open links within Neko rooms.
I am considering if such functionality can be implemented using URL parameters like http://domain/neko-room/?search=www.youtube.com

**Comment by m1k1o** [comment]
There is currently no such feature, there was similar question earlier: https://github.com/m1k1o/neko-rooms/issues/95

**Comment by narainaDewasi** [comment]
thanks for quick response 👍
