### ISSUE TITLE
Question: Is there any way to save browser data through closing or restart?

### ISSUE THREAD

**Issue by nanospearing** [m1k1o/neko-rooms#123]
I would like to start using Neko-rooms instead of Kasm workspaces because of how lightweight it is. One thing that is stopping me though, is that I can't seem to find out how to create persistent storage for the web browsers. Every time I close the virtual browser, I would the browser data to remain. Is this at all possible with Neko rooms in it's current state?

**Comment by m1k1o** [comment]
Yes, its possible. You need to configure storage: https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md

And when starting a browser you can choose in neko rooms, (last section - browser policy) to have it persistent.

**Comment by nanospearing** [comment]
> Yes, its possible. You need to configure storage: https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md
> 
> And when starting a browser you can choose in neko rooms, (last section - browser policy) to have it persistent.

Thank you so much for the help! I got it to work perfectly and I will now be moving over to neko-rooms!
