### ISSUE TITLE
Bind Mount 'Template' changes to 'Private' after Room creation

### ISSUE THREAD

**Issue by jameskitt616** [m1k1o/neko-rooms#128]
I couldn't figure out when exactly this happens, but it happens to me most of the time.
Whenever i create a new room and create Mount of type 'Template' i fails *most* of the time. After submitting the form, the type for all the mounts changed to 'Private' instead of 'Template'.

**Comment by m1k1o** [comment]
That should be identified according to the path prefixes:
https://github.com/m1k1o/neko-rooms/blob/76c0d28c28c47bfb15353f8580c7aa4dea27601f/internal/room/manager.go#L764-L769

When you inspect the docker container, do you see correct paths? Want to see if thats issue upon sending the form or just wrong visualization in GUI.

**Comment by jameskitt616** [comment]
Upon creation i selected type 'Template'
![image](https://github.com/m1k1o/neko-rooms/assets/52933658/c80737fc-c01d-49de-a1df-213d4bf4456e)

After creating when inspecting the Room it clearly shows 'Private' for both mounts
![image](https://github.com/m1k1o/neko-rooms/assets/52933658/32a1ab3b-279d-4832-8f1f-f29bf1abee86)

When trying to start, it fails.
![image](https://github.com/m1k1o/neko-rooms/assets/52933658/570ff56f-a90b-4e48-98e4-2c73076fb1fe)

**Comment by m1k1o** [comment]
Should be fixed with the latest commit. Can you confirm?

**Comment by jameskitt616** [comment]
I run neko-rooms via docker. So i need to wait for a new image on Dockerhub

**Comment by jameskitt616** [comment]
Also thank you for the insane fast fix.

**Comment by jameskitt616** [comment]
Yes, that fixed it. Thanks, you're awesome! <3
