### ISSUE TITLE
Not asking me to sign in.

### ISSUE THREAD

**Issue by DillFrescott** [m1k1o/neko-rooms#13]
I have Caddy reverse proxying to neko rooms, and when I go to the domain, it works fine, but it doesn't ask me to sign in at all.

What am I doing wrong?

**Comment by DillFrescott** [comment]
I think I'm way over my head in this in terms of technical knowledge. When I use the default docker-compose.yml file to set up neko rooms, it says either bad gateway or "this page isnt redirecting properly"

I have to use the http only docker compose file for it to even work properly.

**Comment by m1k1o** [comment]
The default `docker-compose.yml` is meant only for HTTPs with Traefik. If you use another reverse proxy, that will most likely handle all your certificates and you want to connect to neko-rooms with plain HTTP, thus using `docker-compose.http.yml`.

In HTTP example I included only minimal example, that lacks authentication provier. You can take this line from HTTPS configuration to have set up authentication middleware with traefik:

```yaml
- "traefik.http.routers.neko-rooms.middlewares=basicauth@file"
```

**Comment by DillFrescott** [comment]
Ok thank you!
