### ISSUE TITLE
How to contribute? How to build?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko-rooms#133]
How to contribute? How to build?
Any document like the beyond:
https://github.com/m1k1o/neko/tree/master/.docker

**Comment by m1k1o** [comment]
Similarly. In dev/ folder there are those scripts to `./start` backend, `./serve` frontend.

**Comment by z2labplus** [comment]
but if I run the command ./build
![Uploading 1730471260550.png…]()
and I visit the 89.89.89.170:8080
it show 
![Uploading 1730471307228.png…]()
and I 
docker pull m1k1o/neko:firefox
docker pull m1k1o/neko:chromium
my images
REPOSITORY       TAG        IMAGE ID       CREATED         SIZE
neko_rooms_img   latest     5ca430e3c51e   3 minutes ago   1.1GB
<none>           <none>     cc7e87994a32   7 minutes ago   1.08GB
m1k1o/neko       chromium   cdd351695986   4 days ago      1.29GB
m1k1o/neko       firefox    242ae5b65d72   4 days ago      1.09GB
how to continue ?

**Comment by m1k1o** [comment]
Now run `./serve` in new window and go to `:8081`.

**Comment by z2labplus** [comment]
and I run the 
 ./serve
![1730472086472](https://github.com/user-attachments/assets/fb26b49d-6c2e-4a6d-a9fc-942dd124cc2f)
It raise the error
Using app port: 8080
Using IP address: 172.19.16.16

> client@0.1.0 serve
> vue-cli-service serve

sh: 1: vue-cli-service: not found

**Comment by m1k1o** [comment]
Run `docker run --rm -it --user="$(id -u):$(id -g)" --volume "${PWD}/../client:/app" --entrypoint="npm" --workdir="/app" node:20-bookworm-slim install;` to install npm packages first.

**Comment by z2labplus** [comment]
I run the command 
docker run --rm -it --user="$(id -u):$(id -g)" --volume "${PWD}/../client:/app" --entrypoint="npm" --workdir="/app" node:20-bookworm-slim install; 
and then run the ./serve
it's ok
![1730478464323](https://github.com/user-attachments/assets/042b0e49-8d21-43e2-98c2-9a5b2a81d568)

and then I run the ./start
![1730478494763](https://github.com/user-attachments/assets/447d983b-755c-4fe0-a946-dd9a4beb01af)

when I visit the website 89.89.89.170:8080
![1730478558618](https://github.com/user-attachments/assets/bc4e43fd-4c70-4c44-9938-62e92c46043b)
and it is still can working normal

**Comment by m1k1o** [comment]
You visit then `:8081`. On :`8080` there is only backend, and on `:8081` there is frontend.

**Comment by z2labplus** [comment]
> You visit then `:8081`. On :`8080` there is only backend, and on `:8081` there is fronte
Thank you for your prompt reply
but when I visit the room 
http://150.109.110.81:8080/room/neko/
it show the error 
![image](https://github.com/user-attachments/assets/80df96de-019b-462d-a95b-7d78cb9697af)
what happen,and how to solve it? Thank you very much for your reply

**Comment by m1k1o** [comment]
It uses wrong IP according to your screenshot.

![image](https://github.com/user-attachments/assets/8c34f63c-077e-4f29-8388-0bd3b98f0636)

Start your server with your correct IP:

`NEKO_ROOMS_NAT1TO1=150.109.110.81 ./build `

That will tell your server to use your public IP. Assuming ports are forwarded. And recreate your room.

**Comment by z2labplus** [comment]
> It uses wrong IP according to your screenshot.
> 
> ![image](https://private-user-images.githubusercontent.com/7534274/382352628-8c34f63c-077e-4f29-8388-0bd3b98f0636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0ODE1MDcsIm5iZiI6MTczMDQ4MTIwNywicGF0aCI6Ii83NTM0Mjc0LzM4MjM1MjYyOC04YzM0ZjYzYy0wNzdlLTRmMjktODM4OC0wYmQzYjk4ZjA2MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDFUMTcxMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNhMjg0NTA1ODZiZWFmYmJiMThmNTU2ZGE2YWQ1MjFkMGRiNDFhYWJmMzlhNDA5YWYyOGYzMzBhNjMwMDVjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.n3LZyY5pau8xXmG3sq6ZinfW3YQMp9geK2V-CO1ewKw)
> 
> Start your server with your correct IP:
> 
> `NEKO_ROOMS_NAT1TO1=150.109.110.81 ./build `
> 
> That will tell your server to use your public IP. Assuming ports are forwarded. And recreate your room.

Modify the file build ? or the start file?

**Comment by z2labplus** [comment]
it is work!
I don't know how to express my gratitude
My steps is:

curl -sSL https://get.docker.com/ | CHANNEL=stable bash

sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

git clone https://github.com/m1k1o/neko-rooms.git
cd neko-rooms/dev/

docker pull m1k1o/neko:chromium
export NEKO_ROOMS_NAT1TO1=43.132.156.142
./build
![1730512334991](https://github.com/user-attachments/assets/f18bbb7d-1c65-4a5d-a06b-f412acdec23f)
docker run --rm -it --user="$(id -u):$(id -g)" --volume "${PWD}/../client:/app" --entrypoint="npm" --workdir="/app" node:20-bookworm-slim install;
./serve
![1730512356721](https://github.com/user-attachments/assets/29a14353-23dd-460c-8dc5-7a63f8864a11)
and then add the room in the 
http://43.132.156.142:8081/
![1730512375359](https://github.com/user-attachments/assets/dd6dc1cd-4216-45a8-88a6-e1430b8518c9)
and then visit room  
http://43.132.156.142:8080/room/admin/
![1730512400212](https://github.com/user-attachments/assets/2ab05295-d0c8-40ea-84fb-f0c94b9b458f)
