### ISSUE TITLE
How to add NEKO_FILE_TRANSFER_ENABLED parameters

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko-rooms#134]
How to add the 
NEKO_FILE_TRANSFER_ENABLED: true 
NEKO_FILE_TRANSFER_PATH: "/home/neko"
and make the room can upload file

**Comment by m1k1o** [comment]
You can add envs when creating a room. There is possibility to add extended options. In gui when clicking on add room.

**Comment by z2labplus** [comment]
![d211a227313cc2774dd1121ed2b8070](https://github.com/user-attachments/assets/cda128de-261e-45df-b750-b7d8b1da23ec)
it works thanks very much
