### ISSUE TITLE
How to modify the user password after build the room?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko-rooms#135]
![1730559349576](https://github.com/user-attachments/assets/3db00919-3816-4021-8db9-b1a7214f7c65)
How to modify the user password after build the room? 
any api or how ?

**Comment by z2labplus** [comment]
or add user when the image runing ?

**Comment by m1k1o** [comment]
Currently the room cannot be edited, because all data are stored in ENVs and they cannot be modified, thats limitation of docker. https://github.com/m1k1o/neko-rooms/issues/30

**Comment by z2labplus** [comment]
Thanks very much!
so
How should I transfer control of the browser to someone else?
like ban someone?

**Comment by m1k1o** [comment]
You have to be in the room to do that. You can right click on avatar of the person and take control. You have to be admin.

**Comment by z2labplus** [comment]
Can I kick someone(like person B) out of the room?
Like:
The person B can not visit the room.

**Comment by m1k1o** [comment]
Yes in the context menu inside the room.
![image](https://github.com/user-attachments/assets/3dffe784-8837-449b-92b0-6ab4134e042f)

**Comment by z2labplus** [comment]
> Yes in the context menu inside the room. ![image](https://private-user-images.githubusercontent.com/7534274/382557932-3dffe784-8837-449b-92b0-6ab4134e042f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQyMzEsIm5iZiI6MTczMDY0MzkzMSwicGF0aCI6Ii83NTM0Mjc0LzM4MjU1NzkzMi0zZGZmZTc4NC04ODM3LTQ0OWItOTJiMC02YWI0MTM0ZTA0MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTQyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM5ZThlOTAzNzE0YmVjY2ZlNGU2Y2U4ZGUzNjI2YWJiZjZjNTRmYTkxMmEwYTViZDgzYTRiN2Q0NTk1M2I4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dNKdHLQ3tfXR6ZXZ4sOrVkakKr2aSR5_AtXziF4CxTE)

Thanks very much!

**Comment by z2labplus** [comment]
> > Yes in the context menu inside the room. ![image](https://private-user-images.githubusercontent.com/7534274/382557932-3dffe784-8837-449b-92b0-6ab4134e042f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2NDQyMzEsIm5iZiI6MTczMDY0MzkzMSwicGF0aCI6Ii83NTM0Mjc0LzM4MjU1NzkzMi0zZGZmZTc4NC04ODM3LTQ0OWItOTJiMC02YWI0MTM0ZTA0MmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMTQyNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM5ZThlOTAzNzE0YmVjY2ZlNGU2Y2U4ZGUzNjI2YWJiZjZjNTRmYTkxMmEwYTViZDgzYTRiN2Q0NTk1M2I4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dNKdHLQ3tfXR6ZXZ4sOrVkakKr2aSR5_AtXziF4CxTE)
> 
> Thanks very much!

can I kick someone or ban ip via api
