### ISSUE TITLE
docker build -t m1k1o/neko-rooms:20241106 . but can not connect the room?

### ISSUE THREAD

**Issue by z2labplus** [m1k1o/neko-rooms#137]
This is my step
git clone https://github.com/m1k1o/neko-rooms.git
cd neko-rooms
docker build -t m1k1o/neko-rooms:20241106 .
docker images
![1730883139384](https://github.com/user-attachments/assets/2e21b0ee-ac8d-41ad-ab2e-fc18effd517f)
vim docker-compose.yml   to modify the tag
![1730883195043](https://github.com/user-attachments/assets/b62ac3b5-83fd-4626-8346-b74a929cd597)
docker-compose up
![1730883254283](https://github.com/user-attachments/assets/73eb53dc-fd5c-4e75-8159-a557533963d9)
and then I pull the m1k1o/neko:chromium
docker pull m1k1o/neko:chromium
![1730883302006](https://github.com/user-attachments/assets/5e03eceb-2b47-44a0-a7c3-b1af7f0a61ff)
![1730883316113](https://github.com/user-attachments/assets/f9f53eed-78f6-4635-b720-fbc257edd90d)
and then I create the room with chromium
![1730883345607](https://github.com/user-attachments/assets/296e4e9a-cef0-447c-8367-d2994f0b14be)
but when I connnect the room is faild
why
and how to solve it

**Comment by m1k1o** [comment]
I still see (at least on the screenshot) that you have ˙127.0.0.1` as your NAT1TO1 address. Please make sure to always replace the addresses with your actual.

**Comment by z2labplus** [comment]
I set the IP to the NAT1TO1,thanks very much!

**Comment by z2labplus** [comment]
solve it
