### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by Undertaker-afk** [m1k1o/neko-rooms#138]
i set it up with the script but i only get 3 images and pulling does not help because they dont show up

**Comment by Undertaker-afk** [comment]
![Screenshot 2024-11-06 at 18-59-37 neko-rooms](https://github.com/user-attachments/assets/39341923-f034-443f-b52e-4399eef75e41)

**Comment by Undertaker-afk** [comment]
![Screenshot 2024-11-06 at 19-00-02 neko-rooms](https://github.com/user-attachments/assets/0f9ab7bf-7304-4f32-b43f-bb534d0af9e2)

**Comment by m1k1o** [comment]
Yes that's expected. You can edit docker compose yaml and add more or remove the filter NEKO_ROOMS_NEKO_IMAGES so all will be shown.

**Comment by Undertaker-afk** [comment]
Thank you for the fast support

**Comment by Undertaker-afk** [comment]
Okay but now it shows me peer failed
