### ISSUE TITLE
Need some customization

### ISSUE THREAD

**Issue by MrBoudjemaa** [m1k1o/neko-rooms#14]
Hey, 
I would like to change some things 

* Change max connection to unlimited in panel page 
* Remove chat 
* User can't see controls only volume
* Change logo and color

please include files where i can make changes

Thank you , Appreciate your help

**Comment by m1k1o** [comment]
You cannot have unlimited connections, because you need to allocate port for each user. Meaning, theoretical maximum would be 65.535 ports.

Another three points are not releated to **neko-rooms** but to the **neko** image itself. You are able to use own customized image for neko-rooms.

**Comment by m1k1o** [comment]
Closing this as first point is not posible to do with current technology (would need UDP or TCP mux for single port). And another points are irrelevant for **neko-rooms**, but to the **neko** image itself.
