### ISSUE TITLE
UFW blocking ICE connection

### ISSUE THREAD

**Issue by DillFrescott** [m1k1o/neko-rooms#15]
Ok. Sorry to bother, but I have everything working well except for one issue.

When i enable ufw and allow the ports 80, 443, and the 59000-59049 udp ports, the ICE cant establish a connection with the firewall up.

There must be another port I'm missing that neko needs to run.

**Comment by m1k1o** [comment]
Did you install it with install script? Here can be many networks issues:
 - Do you have correctly forwarded ports to your public IP too?
 - Are forwarded ports UDP as well?
 - Are you not behind NAT?

**Comment by DillFrescott** [comment]
@m1k1o 

I installed it manually. It works fine when ufw is disabled, but when ufw is enabled it can't connect.

**Comment by DillFrescott** [comment]
I have no idea but for some reason ufw being on is breaking it.

**Comment by m1k1o** [comment]
There are no additional ports being used, expect your frontend (in your case tcp 80, tcp 443) and chosen EPR (udp 59000-59049). Since UDP is stateless, it needs to be allowed bidirectionally. Not sure if that is automatically handled by UFW.

I guess you already tried some [stackoverflow hints](https://askubuntu.com/a/541687). Maybe you can drop here your config from `ufw status` or check if IPv4 is set correctly over IPv6.

**Comment by DillFrescott** [comment]
Status: active

To                         Action      From
--                         ------      ----
80/tcp                     ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
59000:59099/udp            ALLOW       Anywhere                  
80/tcp (v6)                ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
59000:59099/udp (v6)       ALLOW       Anywhere (v6)

**Comment by DillFrescott** [comment]
https://i.imgur.com/uIc3CVA.png

**Comment by DillFrescott** [comment]
BTW: I am running the neko rooms instance in a privileged podman container to have better control over multiple services on the machine, but none of the other services are running and the ports are all forwarded correctly from the podman container to the host, and then from the host to the router.

Therefore I don't think that would effect things much.

**Comment by m1k1o** [comment]
That everything seems to be fine. I am going to try with ufw myself, if I can replicate your problem.

Is there a chance, that your ufw is blocking outbount connections to get the IP address? It needs to connect to `http://checkip.amazonaws.com`. Could you try, if you can reach that page from your system when ufw is enabled? You can see it in your initial logs, when neko starts, if there is your correct IP. Of course, if you are passing your external IP with `NEKO_ROOMS_NAT1TO1` then that is irrelevant for you and you should get correct IP.

**Comment by DillFrescott** [comment]
Hmm... not sure. I cant ping `checkip.amazonaws.com` neither on the server or on my personal pc. But `amazonaws.com` works.

I guess I can just not use ufw for now.

**Comment by DillFrescott** [comment]
Podman is basically Red Hat's version of Docker, which, I personally like a lot better. Its possible it does do something to the ip tables that is causing some sort of a confliction with ufw.

For now ill just not use ufw and maybe mess around with it more in the future.

**Comment by m1k1o** [comment]
I have tried podman and it seems more secure than docker. But I don't have it in my test environment yet. I am going to play with it in the future and see, if I can replicate this problem.

**Comment by DillFrescott** [comment]
You may already know this, but just an FYI, if you want to run docker in a podman container, I believe you have to run it --privileged. I tried without and it complained...

**Comment by DillFrescott** [comment]
This is the only app on my server preventing me from enabling ufw. I allowed 80/tcp as well as 59000:59099/udp (100 ports) and i get an error about not being to establish the ICE connection...

**Comment by DillFrescott** [comment]
Nevermind I think I found the issue...

**Comment by madindehead** [comment]
> Nevermind I think I found the issue...

Could you please provide the fix?

**Comment by DillFrescott** [comment]
> issue...

I've had this issue with other programs and it seems to be ufw's fault. You can either use iptables directly or I believe there is an option to enable forwarding on ufw which can also solve the issue.
