### ISSUE TITLE
chown error on private storage when recreating room

### ISSUE THREAD

**Issue by gbrian** [m1k1o/neko-rooms#19]
Hi,

I'm having an error when re-creating a room with private storage.
I'm mapping `/home/heko/.mozilla` folde to keep profile when the room is recreated I get this error:

`chown /data/rooms/U00-gbrian/mozilla/firefox/p3gad2ub.default-esr/lock: no such file or directory`

I think this issue is happening because `lock` is a linked file and that causes a problem with docker container if host and cotainer does not have the same folder struture.

I've commented out the lines below until having a better solution

at https://github.com/m1k1o/neko-rooms/blob/b183c1e0521956f55afcf37c836aab40ad90da87/internal/room/manager.go#L216

**Comment by m1k1o** [comment]
I'd say `chown` should only be done on creating the folder and not on recreating.

Or maybe, if that exists it should change only permission of the folder and not the whole tree structure inside. I'll look into it today.

**Comment by gbrian** [comment]
Great, thanks! Not in a hurry.

Can you use UID and GUID from the user running neko-rooms?

```
	privateStorageUid   = 1000
        privateStorageGid   = 1000

```
I'm setting the values  of `user` at docker-compose.yaml to match with the owner of the private storage.
Does it make sense?
thanks

**Comment by m1k1o** [comment]
That would make sense, although the user needs to match also neko user where it is by default 1000. I don't think, that it is able to be modified right now (only [during building](https://github.com/m1k1o/neko/blob/1800d077d8138bdb23c25028bf4201a0469f91aa/.m1k1o/base/Dockerfile#L60)).

**Comment by gbrian** [comment]
@m1k1o ,
working fine. Thank you so much 👏
