### ISSUE TITLE
Missing capability SYS_ADMIN for neko-rooms

### ISSUE THREAD

**Issue by DJKenzoDE** [m1k1o/neko-rooms#21]
hey from germany ^^

i must set the env variable in the create room screen with the sys-admin to google chrome function or i can it leave blank?

**Comment by m1k1o** [comment]
Hey, you don't need to set any env variables for basic usage. Everything should out of the box.

**Comment by DJKenzoDE** [comment]
ah ok i think (because in your normal neko repo you say must set the sys-admin) but all is okay

**Comment by m1k1o** [comment]
It is added by neko-rooms when creating new room. The neko-room manager itself does not need such permission.

https://github.com/m1k1o/neko-rooms/blob/97c47641bf399299506069f291260180426bf173/internal/room/manager.go#L292-L294
