### ISSUE TITLE
Storage Disabled

### ISSUE THREAD

**Issue by DJKenzoDE** [m1k1o/neko-rooms#22]
Mounts cannot be specified because storage is diabled or unavailable 

^^^^tha is the error text to mount the google chrome policies file

**Comment by m1k1o** [comment]
This section is missing documentation, as it is in WIP. I'll add it soon.

Basically you need to specify this in your docker-compose:

```diff
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ"
      - "NEKO_ROOMS_EPR"
      - "NEKO_ROOMS_NAT1TO1"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT"
      - "NEKO_ROOMS_TRAEFIK_NETWORK"
      - "NEKO_ROOMS_INSTANCE_URL=http://${NEKO_ROOMS_TRAEFIK_DOMAIN}:8080/" # external URL
+      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"
+      - "NEKO_ROOMS_STORAGE_EXTERNAL=/opt/neko-rooms/data"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
+      - "/opt/neko-rooms/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.neko-rooms.rule=Host(`${NEKO_ROOMS_TRAEFIK_DOMAIN}`)"
```

Where:
- `NEKO_ROOMS_STORAGE_INTERNAL` is the directory inside your container.
- `NEKO_ROOMS_STORAGE_EXTERNAL` is the directory outside your container.
- `"/opt/neko-rooms/data:/data"` is volume mount.

Please note, that neko-rooms must be aware of your external storage path, as it is going to mount it to the room itself. That needs to be available to **neko-rooms** as well, in order to manage that folder.

Inside your storage path (e.g. `/opt/neko-rooms/data`) there will be available these mountpoints:

- `/opt/neko-rooms/data/`**`rooms/<room name>/`** where will be stored private room data.
- `/opt/neko-rooms/data/`**`templates/`** where templates. will be accessible.

After setting this, storage will be available.

**Comment by DJKenzoDE** [comment]
can you expalne me how to moun the chrome pilicies file correctly? is the template path correct oder the public etc?

**Comment by m1k1o** [comment]
You can always refer to [google-chrome dockerfile](https://github.com/m1k1o/neko/blob/1800d077d8138bdb23c25028bf4201a0469f91aa/.m1k1o/google-chrome/Dockerfile). In this case, policies are mounted to `/etc/opt/chrome/policies/managed/policies.json`. So you can mount custom file to this location.

For this purpose, template path is corect. You can then store your policies file to e.g. `/opt/neko-rooms/data/templates/policies.json` and have it mounted.
![image](https://user-images.githubusercontent.com/7534274/123510856-161aa380-d67e-11eb-86ae-2a107136246b.png)

**Comment by m1k1o** [comment]
Can you post your docker-compose file here?

**Comment by DJKenzoDE** [comment]
version: "3.7"

networks:
  default:
    attachable: "true"
    name: "${NEKO_ROOMS_TRAEFIK_NETWORK}"

services:
  traefik:
    image: "traefik:2.4"
    restart: "unless-stopped"
    environment:
      - "TZ"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./traefik/usersfile:/usersfile:ro"
      - "./traefik/acme.json:/acme.json"
      - "./traefik/config:/config"

  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ"
      - "NEKO_ROOMS_EPR"
      - "NEKO_ROOMS_NAT1TO1"
      - "NEKO_ROOMS_TRAEFIK_DOMAIN"
      - "NEKO_ROOMS_TRAEFIK_ENTRYPOINT"
      - "NEKO_ROOMS_TRAEFIK_CERTRESOLVER"
      - "NEKO_ROOMS_TRAEFIK_NETWORK"
      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"
      - "NEKO_ROOMS_STORAGE_EXTERNAL=/root/neko-rooms/data"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/neko-rooms/data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-rooms-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko-rooms.entrypoints=${NEKO_ROOMS_TRAEFIK_ENTRYPOINT}"
      - "traefik.http.routers.neko-rooms.rule=Host(`${NEKO_ROOMS_TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.neko-rooms.tls=true"
      - "traefik.http.routers.neko-rooms.tls.certresolver=${NEKO_ROOMS_TRAEFIK_CERTRESOLVER}"
      - "traefik.http.routers.neko-rooms.middlewares=basicauth@file"

**Comment by m1k1o** [comment]
Your config looks OK, I don't see why it is not working. Maybe try to recreate it, with `docker-compose down` and `docker-compose up -d`.

You can explicitly enable storage, if it would be disabled somehow, but this should happen implicitly and should not be needed.

```
 - "NEKO_ROOMS_STORAGE_ENABLED=true"
```

**Comment by DJKenzoDE** [comment]
now its started with the storage enabled true and now im looking to sign in in the browser

**Comment by DJKenzoDE** [comment]
now is all fine but how to create a roomw hitout a password? i.e. to make a public room?

**Comment by m1k1o** [comment]
Empty passwords are not supported now. But you can create arbitrary password and share invitation links with other people. That link could be considered as public room entrance.

You can get it in settings, copying this link:
![image](https://user-images.githubusercontent.com/7534274/123834755-10d08980-d908-11eb-9351-ec16ba208003.png)

**Comment by DJKenzoDE** [comment]
okay thanks ^^ thank you much for the work around the neko project and the fork i and my friends love it ^^

**Comment by codebanesr** [comment]
If you're using a Mac, you'll need to modify your docker-compose.yml file. Here are the changes:

```diff
 services:
   neko-rooms:
-    image: "m1k1o/neko-rooms:latest"
+    build: .
     restart: "unless-stopped"
     environment:
       - "TZ=Europe/Vienna"
@@ -18,7 +18,11 @@ services:
       - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
       - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
       - "NEKO_ROOMS_PATH_PREFIX=/room/"
+      - "NEKO_ROOMS_STORAGE_INTERNAL=/data"
+      - "NEKO_ROOMS_STORAGE_EXTERNAL=./data"    # Changed from /opt/neko-rooms/data
     ports:
       - "8080:8080"
+      - "9222:9222"
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
+      - "./data:/data"
```
