### ISSUE TITLE
[Feature] Automatically stop room when all admins leave

### ISSUE THREAD

**Issue by m1k1o** [m1k1o/neko-rooms#28]
Should be toggle option. For better security.

**Comment by Hammyboo** [comment]
Should be either remove or stop, the admin chooses between the two options what do you think?

**Comment by Hammyboo** [comment]
yeah exactly

**Comment by Hammyboo** [comment]
Question tho, stopping the room stops it from taking any resources? because even when it is stopped the port is still staken, does it apply to the CPU and Ram usage?

**Comment by m1k1o** [comment]
Yes, _stopping the room stops it from taking any resources_. Port allocation stays, because it is part of the initial configuration (when creating a room) and cannot be modified on start (those are docker limitations).

**Comment by Hammyboo** [comment]
Thank you for your answer <3

**Comment by m1k1o** [comment]
Closed in favor of: https://github.com/m1k1o/neko-rooms/issues/76
