### ISSUE TITLE
cant use install script

### ISSUE THREAD

**Issue by cking** [m1k1o/neko-rooms#29]
bash: line 136: syntax error near unexpected token `fi'
    bash: line 136: `fi'

**Comment by m1k1o** [comment]
Some people reported this, als also that first while loops forever. I could not seem to reproduce it. What are your system specs? Amd64? Debian based?

**Comment by cking** [comment]
```
kura@levi:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
kura@levi:~$ uname -a
Linux levi 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux
```

**Comment by cking** [comment]
btw, i have curl on host system installed

**Comment by m1k1o** [comment]
I tried it just now, and I did not get any errors. That script looks correct too, don't see anything wrong on that line. Has it been downloaded correctly?

**Comment by cking** [comment]
only worked after i used it with `bash -x install | tee execution.log` - which shouldnt change the behavior

now i need to move the ports but thats less of a problem. anyway thanks
