### ISSUE TITLE
I Want to customize and install own add-ons in Neko Rooms

### ISSUE THREAD

**Issue by prasanthlrb** [m1k1o/neko-rooms#33]
if it's possible for customize and install own add-ons in Neko Rooms

**Comment by m1k1o** [comment]
Yes, you need to set up [storage](https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md) and then you can use browser policy to install browser extensions. Currently there is specified [list of supported images and addons](https://github.com/m1k1o/neko-rooms/blob/2b842665269503bfcb3d707c2d7761497b606312/client/src/store/state.ts#L128-L203), but it can be extended.

**Comment by prasanthlrb** [comment]
current firefox default install NordVPN and Other add-ons, how can I remove add-ons

**Comment by prasanthlrb** [comment]
I tried your steps but I can't remove add-ons in firefox ex nordvpn

**Comment by madindehead** [comment]
Apologies for commenting on a closed issue. 

I know that this (https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks) is how you enable custom addons/extensions for a specific neko container. 

How do I get that working when using neko rooms?

**Comment by m1k1o** [comment]
@madindehead Right now, on the client there are specified just [some addons](https://github.com/m1k1o/neko-rooms/blob/2b842665269503bfcb3d707c2d7761497b606312/client/src/store/state.ts#L128-L203). But if you use API, you can send any addon-id that will be installed.

On the other hand, you can [mount own policy file](https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks), as you mentioned. That can be done, after enabling [storage](https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md) for neko rooms.

It looks like, on GUI there is missing posibility to add own addon ID. Would be a nice and easy PR.
