### ISSUE TITLE
Adding custom images.

### ISSUE THREAD

**Issue by ranomier** [m1k1o/neko-rooms#41]
So i'm pretty ok with docker and creating images. I wan't to create my own image or change one up.

How would i add them to neko-rooms?

Awesome project BTW, thank you!

**Comment by m1k1o** [comment]
You can specify them in environment variable `NEKO_ROOMS_NEKO_IMAGES`, separated with whitespace. E.G:

```
NEKO_ROOMS_NEKO_IMAGES="my_image:tag another_image:v1 third_image:latest"
 ```

Or if you just change existing neko image, you can reuse existing name and tags. Meaning, `m1k1o/neko:chromium` does need to be the image downloaded from internet, but it can be your own, local.

**Comment by ranomier** [comment]
Uuuh thank you i didn't see that in the documentation.

Thank you!

**Comment by ranomier** [comment]
There is one issue, if i set that variable it replaces all default images. But i would like to just add one. How would i do that?

I created one with https://github.com/u8sand/Baka-MPlayer , if you are interested.

**Comment by m1k1o** [comment]
There is currently no way to just add own image. It replaces all. But you could specify them again.

```bash
-e "NEKO_ROOMS_NEKO_IMAGE=
  m1k1o/neko:firefox
  m1k1o/neko:chromium
  m1k1o/neko:google-chrome
  m1k1o/neko:ungoogled-chromium
  m1k1o/neko:microsoft-edge
  m1k1o/neko:brave
  m1k1o/neko:tor-browser
  m1k1o/neko:vlc
  m1k1o/neko:vncviewer
  m1k1o/neko:xfce
  <own-image>
"
```

**Comment by ranomier** [comment]
understood :) :+1:
