### ISSUE TITLE
how to scale neko-rooms?

### ISSUE THREAD

**Issue by dragonballa** [m1k1o/neko-rooms#48]
trying to understand how would you scale neko-rooms, horizontally, vertically? 

Are each rooms essentially individual servers on its own? 

Does it make sense to host as many rooms as possible on a single server with huge amount of cpu and ram?

**Comment by m1k1o** [comment]
Yes, every neko container is standalone.

In the future version, I would like to support docker swarm (or k8s) that would allow to deploy neko rooms to multiple hosts. But we are not there yet, so only solution would be to host multiple independent neko rooms servers and deploy room to one of it according some logic.

**Comment by gbrian** [comment]
Thanks @m1k1o: Looking forward for docker swarm or k8s. Nowdays I'm running multiple neko-rooms so that will simplyfy a lot maintenance and scalability.

**Comment by dragonballa** [comment]
> Yes, every neko container is standalone.
> 
> In the future version, I would like to support docker swarm (or k8s) that would allow to deploy neko rooms to multiple hosts. But we are not there yet, so only solution would be to host multiple independent neko rooms servers and deploy room to one of it according some logic.

you mean like a load balancer that can do round-robin to a bunch of neko-rooms?

**Comment by m1k1o** [comment]
Yes, something like that.

**Comment by Thelvaen** [comment]
Trying to get a N.eko rooms instance up and running on my Swarm home lab at the moment, here is a couple of pointers I can give you so far:

In your Traefik stack configuration, you need to enable both Swarm provider & Docker provider.

      - --providers.swarm=true
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      
If you plan to use storage, and if said storage is mounted on the network (NFS/CIFS/...) keep in mind that it needs to be mounted manually to the correct path on the host that will provide the service.

In my situation, with that tweak done to Traefik, rooms seems to be reachable at least for the login, I'm strill troubleshooting the UDP thing, the WSS can't establish itself.
