### ISSUE TITLE
Usage on local network

### ISSUE THREAD

**Issue by javaarchive** [m1k1o/neko-rooms#6]
Hello, I am trying to run neko-rooms on my local network. Unfortunately traefik_1 appears to keep trying to use lets encrypt even after I copied the http docker compose. 
```
traefik_1     | time="2021-04-28T20:30:23-07:00" level=error msg="the router neko-rooms-Main-Browser-Room@docker uses a non-existent resolver: lets-encrypt"
```
This line seems to be whats stopping neko_rooms from starting. I can use the external port of 8080 but it only shows the 
"Room is ready!
Requested room is ready, you can join now.
Try to reload page." page with "If you see this page after refresh,
it can mean misconfiguration on your side."
So I'm guessing something is stopping the container from being forwarded correctly

**Comment by m1k1o** [comment]
Hello,

I tried to reproduce your problem but I was not able to.

I created a fresh VM and executed following commands:

```bash
git clone https://github.com/m1k1o/neko-rooms
cd neko-rooms/
cp .env.example .env
vim .env # changed domain name & IP address
docker-compose -f docker-compose.http.yml up -d
```

With that, I was able to create & join room without problems.

If you can give me more information about your specific case, I can look into it.

**Comment by javaarchive** [comment]
Thanks for the quick response. I followed the steps above and was able to get the neko-rooms running, I guess I changed the config way too much before trying the http docker-compose file.
