### ISSUE TITLE
[Question]: How I can increase video bright and quaity? 

### ISSUE THREAD

**Issue by gbrian** [m1k1o/neko-rooms#61]
Hi @m1k1o,

In the screenshot you can see the same "webpage" throught Neko and on client browser. How can I improve the video quality to make it more comfortable? Thanks

<img width="902" alt="image" src="https://user-images.githubusercontent.com/767180/164966586-e548f9b7-6a6a-433c-b624-2a3e12071f3a.png">

**Comment by m1k1o** [comment]
By tweaking various encoding parameters, making the resolution bigger. I think it's out of scope for neko-rooms.
