### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by dragonballa** [m1k1o/neko-rooms#63]
So just testing this on my VPS, everything works good, I am able to see the webpage, however when I click on pull image button and choose a browser and click start, a modal shows up with the following message. I tried to search through the code to see what could be causing the issue (github search) but couldn't find anything..

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker 
daemon running?
```

**Comment by m1k1o** [comment]
Have you included `- "/var/run/docker.sock:/var/run/docker.sock:ro"` in your docker-compose?

If yes, do you run rootless doker? If yes, you might have permission problem that the user that runs docker has no access to the docker socket.
