### ISSUE TITLE
[Feature request] Add a copy to clipboard button.

### ISSUE THREAD

**Issue by ranomier** [m1k1o/neko-rooms#66]
![image](https://user-images.githubusercontent.com/7649949/182827814-83c751ac-9730-44fa-86c8-3a279ddbccd5.png)

Right beside the "open link" button please make a copy to clipboard button

Have a wonderful day!

**Comment by m1k1o** [comment]
![image](https://user-images.githubusercontent.com/7534274/182941492-07a75634-5a33-4d2d-8a1f-f30b5b1c8f53.png)
![image](https://user-images.githubusercontent.com/7534274/182941509-7af9a4ef-0740-4298-b250-1f6c50a24056.png)
![image](https://user-images.githubusercontent.com/7534274/182941535-b50fac08-d0e1-48c9-b9e2-17def952484b.png)

**Comment by ranomier** [comment]
Noooooiiiice! Thank you!
