### ISSUE TITLE
Hardware acceleration support?

### ISSUE THREAD

**Issue by DX37** [m1k1o/neko-rooms#67]
Hello there! Using Neko recently, figured how to pass render devices through to docker image and enabled `NEKO_HWENC` for better stream encoding performance.

But in neko-rooms I don't see such options or fields to specify it manually, only `NEKO_HWENC: true`, which cause created room to collapse due to lack of render devices.

Can it be implemented? Is there temporary solution alongside using Neko without rooms?

**Comment by m1k1o** [comment]
You should be able to set `NEKO_HWENC=VAAPI` env variable, add `/dev/dri` to mounts whitelist and mount it as public path. That should be enough, to get it working.

**Comment by DX37** [comment]
> You should be able to set `NEKO_HWENC=VAAPI` env variable, add `/dev/dri` to mounts whitelist and mount it as public path. That should be enough, to get it working.

Nope, that didn't worked. Created room-container falling in fatal state, saying `no vaapivp8enc element`. I tested hardware encoding separately, without rooms and with devices, and it's working on my PC.

**Comment by DX37** [comment]
That's weird, because with mounting and without setting `NEKO_HWENC=VAAPI` I can see `/dev/dri` on any other dirs mounted.
![изображение](https://user-images.githubusercontent.com/12829428/182891933-1e40b173-e3d2-4a31-9a36-dd8d5899ed4f.png)

**Comment by DX37** [comment]
Hey, can it be because of different groups of `card0` and `renderD128`? This is from Neko without rooms.
![изображение](https://user-images.githubusercontent.com/12829428/182902208-6a5eeb52-9bd8-4fa1-be5f-36950b20c294.png)

**Comment by m1k1o** [comment]
I don't have such GPU, so I cannot help further. Here is original PR https://github.com/m1k1o/neko/pull/151 for that, maybe the author can help you with that

**Comment by DX37** [comment]
> I don't have such GPU, so I cannot help further. Here is original PR [m1k1o/neko#151](https://github.com/m1k1o/neko/pull/151) for that, maybe the author can help you with that

I'm not asking for help for GPU support, I asking is there a way to add option for adding docker-compose devices string for rooms creating?

**Comment by m1k1o** [comment]
No, that is not possible with neko-rooms yet. This is how it could look like: https://github.com/m1k1o/neko-rooms/commit/35d2958883f0a9ef699905eb80b70159896de557 Or alternatively just implementing `gpu: enum` for room and it mounts correct devices/sets correct env.
