### ISSUE TITLE
[Question] ARM Images in rooms?

### ISSUE THREAD

**Issue by wajwuz** [m1k1o/neko-rooms#70]
In normal neko i can use `m1k1o/neko:arm-chromium` which i can't found while creating a room in rooms
![image](https://user-images.githubusercontent.com/75165095/183287604-b61d12fa-2b07-41a4-99f8-8cc386d41637.png)

**Comment by m1k1o** [comment]
ARM images are not build automatically in CI yet. You should rebuild them to have latest version. Then you can add it to the list using this enviroment vaitable: `NEKO_ROOMS_NEKO_IMAGES=m1k1o/neko:arm-chromium`.

**Comment by Eris7090** [comment]
> ARM images are not build automatically in CI yet. You should rebuild them to have latest version. Then you can add it to the list using this enviroment vaitable: `NEKO_ROOMS_NEKO_IMAGES=m1k1o/neko:arm-chromium`.

This is a real noob question, but where do I add that?

Right now I'm using an oracle cloud VM that's arm and every time I create a room it just gets stuck restarting and I think it's because I need the arm version

**Comment by m1k1o** [comment]
@Eris7090 to env variables, e.g. here: https://github.com/m1k1o/neko-rooms/blob/c325d4fc59dd75e97015bcb63c19987362d83a54/docker-compose.yml#L12-L20

Or if you have `env_file: .env` then in `.env` file.

**Comment by m1k1o** [comment]
We have new arm images:

```
-e "NEKO_ROOMS_NEKO_IMAGES=ghcr.io/m1k1o/neko/arm-firefox:latest ghcr.io/m1k1o/neko/arm-chromium:latest ghcr.io/m1k1o/neko/arm-ungoogled-chromium:latest ghcr.io/m1k1o/neko/arm-vlc:latest ghcr.io/m1k1o/neko/arm-xfce:latest"
```

Adding this will allow you to use arm images.
