### ISSUE TITLE
The Neko-Rooms docker image still requires traefik and is not using the custom proxy added in the 1.5 update.

### ISSUE THREAD

**Issue by Xeddius** [m1k1o/neko-rooms#71]
I have installed neko-rooms and upon creating a room I get the error. 
![image](https://user-images.githubusercontent.com/6382895/186367083-0d9a71ce-8d35-4aa1-bd7d-54b4b0a4991b.png)

**Comment by m1k1o** [comment]
It sill needs docker network that connects all neko rooms with its reverse proxy. Default name (when not specified) is simply traefik (to maintain backward compatibility).

You can change it using `NEKO_ROOMS_INSTANCE_NETWORK=your-network-name`. It should be generally the network set in docker-compose:

https://github.com/m1k1o/neko-rooms/blob/41facda0bc80774596c5a194ddf6ee6f54c495e2/docker-compose.yml#L3-L6

It is specified as ENV here:

https://github.com/m1k1o/neko-rooms/blob/41facda0bc80774596c5a194ddf6ee6f54c495e2/docker-compose.yml#L18.

**Comment by m1k1o** [comment]
And you need to specify `NEKO_ROOMS_TRAEFIK_ENABLED=false` because by default it is true, again, to maintain backward compatibility as it was always by default enabled.
