### ISSUE TITLE
mobile browser

### ISSUE THREAD

**Issue by 809509941** [m1k1o/neko-rooms#72]
Is it possible for neko-rooms to add a mobile browser?
Nowadays, people use smartphones more frequently.I've been looking for a long time and I haven't found a shared browser solution that works on smartphone touch screens yet.Also can the script set the option to add other images?This way people can choose what they need.

**Comment by m1k1o** [comment]
This is only orchestrator, original feature request belongs to neko repository. And there is already one for mobile keybaord: https://github.com/m1k1o/neko/issues/115
