### ISSUE TITLE
Browser Extensions

### ISSUE THREAD

**Issue by Gagtech** [m1k1o/neko-rooms#77]
I recently came across this software as an alternative to watchparty.me (it seems to use similar tech).
It looks like the VPS provider I'm using is getting blocked by Netflix because I get an error 403, permission denied when trying to access it.

I looked at enabling a VPN extension, but it looks like that's disabled by admin?

**Comment by m1k1o** [comment]
Actually watchparty.me uses [neko under the hood](https://github.com/howardchung/watchparty/issues/547), only they forgot to admit it.

It is disabled by policy, you can either make policy more relaxed (not disabling extensions) or add your own extension, see docs:
https://neko.m1k1o.net/#/getting-started/?id=want-to-customize-and-install-own-add-ons-set-custom-bookmarks

Or you could use [neko-rooms](https://github.com/m1k1o/neko-rooms/) where policy generated exists. Depending on your usecase.

**Comment by Gagtech** [comment]
Yea, as soon as I saw the browser desktop I was like... huh that's familiar. 

Ok, thanks. I'll take a look.
