### ISSUE TITLE
reconnects

### ISSUE THREAD

**Issue by 809509941** [m1k1o/neko-rooms#78]
Every few minutes it disconnects and then reconnects.
![image](https://user-images.githubusercontent.com/62390747/203704787-93a0a23b-79dc-4c29-ab28-91e990ca551a.png)

**Comment by 809509941** [comment]
![image](https://user-images.githubusercontent.com/62390747/203707623-60c52359-cb05-4c6f-ad83-d0d5e3b57b10.png)

**Comment by m1k1o** [comment]
Do you have it behind own reverse proxy? Looks like websockets timeout is less than 60sec. Or look at [troubleshooting](https://neko.m1k1o.net/#/getting-started/troubleshooting) docs.

**Comment by m1k1o** [comment]
Can't reproduce.
