### ISSUE TITLE
How to increase shared memory size?

### ISSUE THREAD

**Issue by impromedia** [m1k1o/neko-rooms#82]
I want to run an Ubuntu game inside the container and I need to increase the shared memory size.
I've tried on the neko-rooms ADD ROOM / expert setings to add a new key shm_size and value '16gb' without success.
It seems that the value of shm_size is hardcoded to 2GB
Can you help me? Thank you.

**Comment by m1k1o** [comment]
It is available in [API](https://github.com/m1k1o/neko-rooms/blob/3ef638715321e8282340818303503aa837e237b1/OpenApi.yml#L345) but currently not in GUI.

You could add it to default room variables, that are stored in VUEx store. Run this in your console:

```javascript
// from https://stackoverflow.com/a/69466883/1113204 
var vue = Array.from(document.querySelectorAll('*')).find(e => e.__vue__).__vue__
// set custom settings
vue.$store.state.defaultRoomSettings.resources =  { shm_size: 3000000000 }
```

Every room created in that page (until refreshed) will have specified values.
