### ISSUE TITLE
Setting NAT configuration but still getting timeout

### ISSUE THREAD

**Issue by Busbar2297** [m1k1o/neko-rooms#88]
Hi,
I have set the environment to the NAT IP I should use, I am using 
      - "NEKO_ROOMS_NAT1TO1=192.168.32.142"
This worked once but new images are not working and getting timeout connection, tried update images with no luck and i am getting socket connection timeout, what could be the issue ?!

**Comment by Busbar2297** [comment]
Ok, After some playing around, I found that when I add a new room, I can't to all rooms unless I force recreate the images, why is that ?!

**Comment by m1k1o** [comment]
All rooms that are created will be using that IP. `NEKO_ROOMS_NAT1TO1` is read and added to a room `NEKO_NAT1TO1` upon creation. Even if you change `NEKO_ROOMS_NAT1TO1` and neko room is still running, it won't update it. You need to recreate it.

**Comment by Busbar2297** [comment]
I found that if I am using traefik as proxy and adding new rooms, everything stops until I redeploy all rooms, but once I removed it and did direct connectivity, everything worked normally. not sure if anyone else saw this.
