### ISSUE TITLE
Add the latest NVIDIA docker image on neko-rooms

### ISSUE THREAD

**Issue by Uruknara** [m1k1o/neko-rooms#89]
Hello, just wanted to know if you missed it or im doing something wrong but where can i get the new image with docker nvidia ?

**Comment by m1k1o** [comment]
Hello, I am currently buidling them. Once done, they will be avaliable here:
https://neko.m1k1o.net/#/getting-started/

![image](https://user-images.githubusercontent.com/7534274/225974258-293aa6b0-f9b1-419e-a082-ed2ce1211690.png)


But currently they are not part of neko-rooms so you could add them manually to ENV:
```
NEKO_ROOMS_NEKO_IMAGES="ghcr.io/m1k1o/neko/nvidia-chromium:latest ghcr.io/m1k1o/neko/nvidia-google-chrome:latest ghcr.io/m1k1o/neko/nvidia-microsoft-edge:latest ghcr.io/m1k1o/neko/nvidia-brave:latest"
```

And do not forget in expert settings, when creating room, add gpu.

I'll notify you when they are available.

**Comment by Uruknara** [comment]
Thank you so much gonna try this out right now ^^

**Comment by Uruknara** [comment]
Ok i tested Brave image on local network with neko on LXC by proxmox and is just so much fluid like for everything 

Just watching youtube video and moving cursor is a lot faster than ever

**Comment by m1k1o** [comment]
Glad to hear that! Now all others are avaliable.
https://github.com/m1k1o?tab=packages&tab=packages&q=nvidia

**Comment by Uruknara** [comment]
Oh little problem i think cause i was wanting to test and compare in real time with another brave but without nvidia and tried to pull the image but just neko-rooms won't finish downloading it look 

[https://img.uruk.dev/‌​‍⁠⁠‍⁠‌​⁠​⁠‌‍​](url)

**Comment by Uruknara** [comment]
Oh strange now i can't download any image ?

**Comment by Uruknara** [comment]
Oh my god sorry but i was not having enought space on my CT so it just can't download it but strange that neko-rooms doesn't show me the error from docker and just closed the window

**Comment by m1k1o** [comment]
Yeah, thats a good point. I guess i never tried such edge case. It should show error, would be easier to debug.

**Comment by Uruknara** [comment]
> Yeah, thats a good point. I guess i never tried such edge case. It should show error, would be easier to debug.

Of course !

**Comment by Uruknara** [comment]
Last question i think but why can't we when having a gpu make room in 4k60 ?

**Comment by Uruknara** [comment]
Thanks for every reply and yes maybe you will find a better package for chromium cause 83 is like very old and we don't have the full capacity of the navigator ^^

And in the future encoding would be so much cooler so we can use HEVC and all other codec and have a complete compatibility with everything and so much less use of the CPU

Another time thank you very much and have an absolutely wonderful day ☺️
