### ISSUE TITLE
When recreating the room to update it how do you keep the persistent data from the previous image?

### ISSUE THREAD

**Issue by GabrielSerealia** [m1k1o/neko-rooms#93]
Would naming it the same essentially do that?
Or would I have to do it manually via the CLI?

**Comment by m1k1o** [comment]
If you created persistent rooms (see image) then yes, rectreating the room will persist the data - though only browser data (if you installed something manually that won't be persisted). In that case naming it the same would also do the job.

![image](https://github.com/m1k1o/neko-rooms/assets/7534274/ebe414d4-e70a-4698-b44c-c72207d2b3a8)

**Comment by GabrielSerealia** [comment]
Hey thanks a lot!
