### ISSUE TITLE
Room constantly refreshing. Never loads.

### ISSUE THREAD

**Issue by ZTexX** [m1k1o/neko-rooms#94]
The room just keeps refreshing and randomly turns off. It never starts. Constantly says room is not ready yet. The error I'm getting is a 500 internal server error in the console with stats request.

**Comment by m1k1o** [comment]
Could you please log in to ssh of your server, locate your room in `docker ps` command and show logs using `docker logs <container-name>` ? It is apparently not starting properly and in restart loop.

**Comment by m1k1o** [comment]
Cannot reproduce.
