### ISSUE TITLE
Starter page for each room using mounts.

### ISSUE THREAD

**Issue by Armrisch1** [m1k1o/neko-rooms#96]
Sorry for additional question.
I know there is a way to set default url using mounts in neko, I want to figure out how can I do it using neko rooms, where I need to create google-chrome.conf for specific room?
I found this https://github.com/m1k1o/neko-rooms/blob/master/docs/storage.md. 
I enabled storage, used mounts private type, but I cant figure out what host_path and container_path I need to set.
Thanks for advance.

**Comment by m1k1o** [comment]
> I know there is a way to set default url using mounts in neko

I guess you mean browser policy, right? Or supervisord (from here https://github.com/m1k1o/neko/issues/312)?

For this kind of of mounts, that are readonly you can use `template`.

Container path can be [read from Dockerfile](https://github.com/m1k1o/neko/blob/8ef9c1aff5d68bfec22382ee60ecfa2c93bba752/.docker/google-chrome/Dockerfile#L18), it is `/etc/neko/supervisord/google-chrome.conf`. Host path for tempate mount type can be just the name of the file e.g. [`google-chrome.conf`](https://github.com/m1k1o/neko/blob/master/.docker/google-chrome/supervisord.conf) and then you put that file in your storage data folder in `templates/google-chrome.conf`.

![image](https://github.com/m1k1o/neko-rooms/assets/7534274/3829522a-5f31-4960-83f1-4ca32376c811)
![image](https://github.com/m1k1o/neko-rooms/assets/7534274/2fd7247e-8c69-4438-b59e-939094498375)

**Comment by Armrisch1** [comment]
![Screenshot_1](https://github.com/m1k1o/neko-rooms/assets/84318547/721b754a-7969-4f33-bad1-7a61631d5fa6)
![Screenshot_2](https://github.com/m1k1o/neko-rooms/assets/84318547/fa2128bf-12a9-42d8-ac41-3f68bda66330)
![Screenshot_3](https://github.com/m1k1o/neko-rooms/assets/84318547/74718704-ac67-4a86-811e-e222edd77025)

I did this steps, but it still not open youtube as default page of room browser, do you have any idea why? Maybe  I am doing something wrong?

**Comment by m1k1o** [comment]
You are almost right, only make sure that it is part of the command arguments for google-chrome. They are either space separated, all in one line (like in your case, so put`--kiosk="https://youtube.com/"` right after `--disable-dev-shm-usage`). Or in [multiple lines](https://github.com/m1k1o/neko/blob/8ef9c1aff5d68bfec22382ee60ecfa2c93bba752/.docker/google-chrome/supervisord.conf#L3-L14), where every argument is prefixed with whitespaces:

And that `URL=...` should be removed.

So example:

```conf
[program:google-chrome]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/google-chrome
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=/home/neko/.config/google-chrome
  --no-first-run
  --start-maximized
  --bwsi
  --force-dark-mode
  --disable-file-system
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
  --kiosk="https://youtube.com/"
stopsignal=INT
autorestart=true
...
```

or:

```conf
[program:google-chrome]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/google-chrome --window-position=0,0 --display=%(ENV_DISPLAY)s --user-data-dir=/home/neko/.config/google-chrome --no-first-run --start-maximized --bwsi --force-dark-mode --disable-file-system --disable-gpu --disable-software-rasterizer --disable-dev-shm-usage --kiosk="https://youtube.com/"
stopsignal=INT
autorestart=true
...
```

**Comment by Armrisch1** [comment]
I fixed issues as you said, but effect is other, it hid browser address bar, any ideas why?
![Screenshot_4](https://github.com/m1k1o/neko-rooms/assets/84318547/c032a63f-c9de-42d8-afd6-39da07cf4970)
![Screenshot_5](https://github.com/m1k1o/neko-rooms/assets/84318547/19e04c1a-1388-44ab-ba8f-2632e3d3a789)

**Comment by m1k1o** [comment]
That does kiosk mode. You could remove `--kiosk=` and leave only URL there. Then it should not hide browser bar.

**Comment by Armrisch1** [comment]
![Screenshot_6](https://github.com/m1k1o/neko-rooms/assets/84318547/b0a4587a-e031-417a-be6b-80412ffdacde)
I tried this but this also not working.

**Comment by Armrisch1** [comment]
Thanks a lot finnaly it works.
![Screenshot_6](https://github.com/m1k1o/neko-rooms/assets/84318547/d423dab7-6800-4f4b-86d8-0b4232698b9b)
Last question, there is a way to hide sponsor block?

**Comment by m1k1o** [comment]
It cannot be hidden unfortunately, only removed.

choose it in Browser policy menu in neko rooms. Or edit policy file that i see you are including. There is extension install list and the id of sponsorblock.

**Comment by Armrisch1** [comment]
Ok, Thanks a lot.
