### ISSUE TITLE
Change scroll sensitivity using neko api.

### ISSUE THREAD

**Issue by Armrisch1** [m1k1o/neko-rooms#99]
Is there a way to change scroll sensitivity using neko open api, now we can change scroll sensitivity from neko settings manually but I need to do it from api.
Because scroll is very fast by default.

Thanks for advance!

**Comment by m1k1o** [comment]
Hello, that is currently not possible because that information is never stored on backend. It is only available in client therefore it is not configurable from API.

**Comment by Armrisch1** [comment]
May be it is possible to set some default sensitivity for all rooms? For example when n.eko is building or do it in some other way. 
Default scroll is too fast now and it is not comfortable to use.

**Comment by m1k1o** [comment]
You could change it in [client store here](https://github.com/m1k1o/neko/blob/052a961fd948de83d68ffdeb698976a458ab3c8f/client/src/store/settings.ts#L14) and build custom image that can be used in new value.

But I agree with you that the default sensitivity is not optimal (and as well dependent on OS and browser) and could be reconsidered.

**Comment by Armrisch1** [comment]
Thanks but I am using n.eko rooms, how can I do it with neko rooms, as I know each room is a new docker container bulit by n.eko,  what I need to change in n.eko rooms?

**Comment by Armrisch1** [comment]
Sorry for so many questions. But where I need to clone neko and build that neko-rooms starts using my local neko?

**Comment by m1k1o** [comment]
Anywhere on your system, e.g. your `$HOME` directory `/home/user` or `/opt` or `/tmp`.

```bash
git clone https://github.com/m1k1o/neko
cd neko
# ... do your changes
cd .docker
./build base
./build chromium
```

Now you have successfully build your custom `m1k1o/neko:chromium` image. Everytime there is update just do `git pull origin master` and rebuild again.

Don't worry that it is named the same as the official image but it contains your changes. Of course, only on that server where you built that.

**Comment by Armrisch1** [comment]
Thanks a lot.
